FROM ubuntu:latest

# System aktualisieren und benötigte Pakete installieren
RUN apt-get update && \
  apt-get install -y \
  php \
  php-cli \
  php-mbstring \
  php-xml \
  php-bcmath \
  php-curl \
  php-mysql \
  php-tokenizer \
  php-zip \
  php-intl \
  unzip \
  curl \
  git \
  nodejs \
  npm \
  composer \
  && apt-get clean